INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Dragon Ball Z', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yfyToia25GnvjY7FPAGaCm3lKRc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Boruto: The movie', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1k6iwC4KaPvTBt1JuaqXy3noZRY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tokyo Ghoul', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/y2roOFsew9nJKKVwwJCHSyzgpK9.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Boku no Hero', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Death Note', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Attack on Titan', 'https://derf9v1xhwwx1.cloudfront.net/image/upload/c_fill,q_80,w_265,h_397/oth/FunimationStoreFront/1287817/Portuguese(Brazil)/1287817_Portuguese(Brazil)_ShowKeyart_9cdb6bf7-0600-41b6-858d-82f5816f856e.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Arifureta: From Commonplace to Worlds Strongest', 'https://derf9v1xhwwx1.cloudfront.net/image/upload/c_fill,q_80,w_265,h_397/oth/FunimationStoreFront/2022001/Japanese/2022001_Japanese_ShowKeyart_2c256044-3764-4e5b-9880-602b45a89c89.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Demon Slayer: Kimetsu no Yaiba', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wrCVHdkBlBWdJUZPvnJWcBRuhSY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'CODE GEASS', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ghD2HJyAk6EYVHrzBhddNDJ73Go.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Assassination Classroom', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qf0l0nQ2t06Es3cSXflqx6l6vsJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Promised Neverland', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sword Art Online', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mpJhsU1whSvAE1Ed0bR7ZA52aZq.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Overlord', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aSjpVCanDAwCopdjIgWwrxOWnWf.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Seraph of the End', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5IlxL2PfQ8CyY4TLRru9TcU56b3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fire Force', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zLDxWMM0BLImdAsnkqGeeoqjYev.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Rage of Bahamut Genesis', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/osUNCb2v2kIlyLg9DgM5zBlnyRB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Future Diary', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eQBO8pyuch83TonVJc2NMFv7W8U.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cowboy Bebop', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lSsCxZ1dnjcB4cmXSgMJt5qunOu.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Gleipnir', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eF1kUIoyL2dxPGGsxNXYrkrAPs2.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fairy Tail', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jsYTctFnK8ewomnUgcwhmsTkOum.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Rascal Does Not Dream of Bunny Senpai', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7Ai8vNEv4zEveh12JViGikoVPVV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Ones Within', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vT1oUjqaLLNz1XcHrSE9EnbFre3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'She Professed Herself Pupil of the Wise Man', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bINehsK3ge0y3oCyrFntnKn7R7D.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sekai Ichi Hatsukoi - The World Greatest First Love', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/cqkTthn03IlbeEnDaclZ0CPdiSC.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kakushigoto', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/odtryn9XCRIo33oLDaAaaTNgiuQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pokémon', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rOuGm07PxBhEsK9TaGPRQVJQm1X.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shaman King', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bDJLF92frEmKSr1OlCZN5P1kx6W.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Yu gi oh', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uQshAcOLRi5o1KEeuXfMswA8JOE.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Yu Yu Hakusho', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fOD3EVUGWLxmeAfdloBjLwaucGC.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);